FROM php:7.4-apache
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli && docker-php-ext-install pdo_mysql
RUN a2enmod rewrite && a2enmod ssl && a2enmod socache_shmcb
RUN sed -i '/SSLCertificateFile.*snakeoil\.pem/c\SSLCertificateFile \/etc\/ssl\/certs\/azcamarketingportafolio.jeelidev.online.pem' /etc/apache2/sites-available/default-ssl.conf && sed -i '/SSLCertificateKeyFile.*snakeoil\.key/cSSLCertificateKeyFile /etc/ssl/private/azcamarketingportafolio.jeelidev.online-key.pem\' /etc/apache2/sites-available/default-ssl.conf
RUN a2ensite default-ssl
RUN usermod -u 1000 www-data && groupmod -g 1000 www-data
RUN apt-get update && apt-get upgrade -y
COPY ./php.ini-develop /usr/local/etc/php/php.ini
EXPOSE 443
EXPOSE 80