version: "3.8"

services:
  wordpress:
    build:
      context: . # Utiliza el Dockerfile desde el directorio actual
    env_file:
      - .env
    ports:
      - "8080:80"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    volumes:
      - .:/var/www/html
