version: "3.8"

services:
  wordpress:
    build:
      context: . # Utiliza el Dockerfile desde el directorio actual
    env_file:
      - .env
    ports:
      - "443:443"
    environment:
      - DB_NAME=${WORDPRESS_DB_NAME}
      - DB_USER=${WORDPRESS_DB_USER}
      - DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - DB_HOST=${WORDPRESS_DB_HOST}
    volumes:
      - .:/var/www/html
