services:
  webserver:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8080:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: myqldb:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: sgkxOSxSKVXFDcbpMOYvamAFtPCSESsg
      WORDPRESS_DB_NAME: railway
    volumes:
      - ./html:/var/www/html
      - ./certs/azcamarketingportafolio.jeelidev.online.pem:/etc/ssl/certs/azcamarketingportafolio.jeelidev.online.pem
      - ./certs/azcamarketingportafolio.jeelidev.online-key.pem:/etc/ssl/private/azcamarketingportafolio.jeelidev.online-key.pem

  db:
    container_name: myqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: sgkxOSxSKVXFDcbpMOYvamAFtPCSESsg
    volumes:
      - ./db:/var/lib/mysql
      - ./backups/:/docker-entrypoint-initdb.d

volumes:
  html:
  db:
